### ISSUE TITLE
Kick.com seems broke

### ISSUE THREAD

**Issue by warpz0ne88** [jenslys/autovod#85]
**Describe the bug**
cant find running kick streams..

**Show logs**
```
12|rainerwinklerdl          | 11:25:30| Trying to fetch stream metadata
12|rainerwinklerdl          | 11:25:31| Stream seems offline, not able to fetch metadata.
12|rainerwinklerdl          | 11:25:31| Checking kick.com/rainerwinklerdl for a stream
12|rainerwinklerdl          | 11:25:31| All required files found
12|rainerwinklerdl          | [session][error] Failed to load plugin nicolive from /home/stoned/.local/lib/python3.11/site-packages/streamlink/plugins
12|rainerwinklerdl          | Traceback (most recent call last):
12|rainerwinklerdl          |   File "/home/stoned/.local/lib/python3.11/site-packages/streamlink/session.py", line 649, in load_plugins
12|rainerwinklerdl          |     mod = load_module(module_name, path)
12|rainerwinklerdl          |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12|rainerwinklerdl          |   File "/home/stoned/.local/lib/python3.11/site-packages/streamlink/utils/module.py", line 14, in load_module
12|rainerwinklerdl          |     spec.loader.exec_module(mod)
12|rainerwinklerdl          |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
12|rainerwinklerdl          |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
12|rainerwinklerdl          |   File "/home/stoned/.local/lib/python3.11/site-packages/streamlink/plugins/nicolive.py", line 19, in <module>
12|rainerwinklerdl          |     from streamlink.plugin.api.websocket import WebsocketClient
12|rainerwinklerdl          |   File "/home/stoned/.local/lib/python3.11/site-packages/streamlink/plugin/api/websocket.py", line 8, in <module>
12|rainerwinklerdl          |     from websocket import ABNF, STATUS_NORMAL, WebSocketApp, enableTrace  # type: ignore[attr-defined,import]
12|rainerwinklerdl          |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12|rainerwinklerdl          | ImportError: cannot import name 'ABNF' from 'websocket' (/home/stoned/.local/lib/python3.11/site-packages/websocket/__init__.py)
12|rainerwinklerdl          | [session][error] Failed to load plugin twitcasting from /home/stoned/.local/lib/python3.11/site-packages/streamlink/plugins
12|rainerwinklerdl          | Traceback (most recent call last):
12|rainerwinklerdl          |   File "/home/stoned/.local/lib/python3.11/site-packages/streamlink/session.py", line 649, in load_plugins
12|rainerwinklerdl          |     mod = load_module(module_name, path)
12|rainerwinklerdl          |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12|rainerwinklerdl          |   File "/home/stoned/.local/lib/python3.11/site-packages/streamlink/utils/module.py", line 14, in load_module
12|rainerwinklerdl          |     spec.loader.exec_module(mod)
12|rainerwinklerdl          |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
12|rainerwinklerdl          |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
12|rainerwinklerdl          |   File "/home/stoned/.local/lib/python3.11/site-packages/streamlink/plugins/twitcasting.py", line 17, in <module>
12|rainerwinklerdl          |     from streamlink.plugin.api.websocket import WebsocketClient
12|rainerwinklerdl          |   File "/home/stoned/.local/lib/python3.11/site-packages/streamlink/plugin/api/websocket.py", line 8, in <module>
12|rainerwinklerdl          |     from websocket import ABNF, STATUS_NORMAL, WebSocketApp, enableTrace  # type: ignore[attr-defined,import]
12|rainerwinklerdl          |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12|rainerwinklerdl          | ImportError: cannot import name 'ABNF' from 'websocket' (/home/stoned/.local/lib/python3.11/site-packages/websocket/__init__.py)
12|rainerwinklerdl          | [session][error] Failed to load plugin ustreamtv from /home/stoned/.local/lib/python3.11/site-packages/streamlink/plugins
12|rainerwinklerdl          | Traceback (most recent call last):
12|rainerwinklerdl          |   File "/home/stoned/.local/lib/python3.11/site-packages/streamlink/session.py", line 649, in load_plugins
12|rainerwinklerdl          |     mod = load_module(module_name, path)
12|rainerwinklerdl          |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12|rainerwinklerdl          |   File "/home/stoned/.local/lib/python3.11/site-packages/streamlink/utils/module.py", line 14, in load_module
12|rainerwinklerdl          |     spec.loader.exec_module(mod)
12|rainerwinklerdl          |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
12|rainerwinklerdl          |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
12|rainerwinklerdl          |   File "/home/stoned/.local/lib/python3.11/site-packages/streamlink/plugins/ustreamtv.py", line 23, in <module>
12|rainerwinklerdl          |     from streamlink.plugin.api.websocket import WebsocketClient
12|rainerwinklerdl          |   File "/home/stoned/.local/lib/python3.11/site-packages/streamlink/plugin/api/websocket.py", line 8, in <module>
12|rainerwinklerdl          |     from websocket import ABNF, STATUS_NORMAL, WebSocketApp, enableTrace  # type: ignore[attr-defined,import]
12|rainerwinklerdl          |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12|rainerwinklerdl          | ImportError: cannot import name 'ABNF' from 'websocket' (/home/stoned/.local/lib/python3.11/site-packages/websocket/__init__.py)
12|rainerwinklerdl          | error: No playable streams found on this URL: kick.com/rainerwinklerdl
12|rainerwinklerdl          | 11:25:32| youtubeuploader failed uploading the stream
12|rainerwinklerdl          | 11:25:32| Trying again in 1 minute
```

**Desktop (please complete the following information):**
debian 11

**Comment by jenslys** [comment]
Have you downloaded and added the https://github.com/nonvegan/streamlink-plugin-kick plugin?

**Comment by jenslys** [comment]
https://github.com/jenslys/autovod/commit/3201e9a92439e204f7f4886694eb2ff1f7fa996b might fix the issue
